language: python
python:
  - "3.6"  
install:    
  - pip install pipenv  
  - pipenv install --dev
  - cp tax_calculator/settings/local.py.example tax_calculator/settings/local.py
  - cp .env.example .env  
  - pipenv run python manage.py makemigrations
  - pipenv run python manage.py migrate  
script:
  - make test
