# Generated by Django 2.1.5 on 2019-01-21 15:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tax_calculator.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_association', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(tax_calculator.models.Exportable, tax_calculator.models.TaxCalculator, models.Model),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tax_calculator.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_code', models.CharField(max_length=50)),
                ('setting_value', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('tax', 'Tax'), ('stock', 'Stock')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('display_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_imported', models.BooleanField(default=False)),
            ],
            bases=(tax_calculator.models.Exportable, models.Model),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('mode', models.CharField(choices=[('fixed', 'Fixed'), ('percentual', 'Percentual')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='productcategory',
            name='additional_tax_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_imported', to='tax_calculator.TaxRate'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='basic_tax_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tax_calculator.TaxRate'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tax_calculator.ProductCategory'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item_association', to='tax_calculator.Product'),
        ),
    ]
